# Generated by Django 5.2 on 2025-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hiring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("model", "Model")],
                default="user",
                max_length=10,
            ),
        ),
    ]
